# This file is auto-generated by nixos-generate-config
# during NixOS installation. Replace with actual generated file.
# WARNING: Delete this placeholder after running nixos-generate-config.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.loader.grub.devices = [ "/dev/sda" ];
  fileSystems."/" = { device = "/dev/sda1"; fsType = "ext4"; };

  # Will be replaced with actual config after install
}
