# hardware-configuration.nix
#
# This file is AUTO-GENERATED by `nixos-generate-config --root /mnt`
# during the NixOS installation process.
#
# Placeholder for now — will be replaced after install.
{ ... }: {}
