# hardware-configuration.nix
#
# This file is AUTO-GENERATED by `nixos-generate-config --root /mnt`
# during the NixOS installation process.
#
# It contains the specific disk layout, filesystem UUIDs, and hardware
# configuration of THIS machine (VM 153).
#
# DO NOT edit this file manually. To regenerate:
#   nixos-generate-config --root /
#
# During install:
#   1. Partition + format + mount
#   2. Run: nixos-generate-config --root /mnt
#   3. Copy the generated file from /mnt/etc/nixos/hardware-configuration.nix
#      into this repo, replacing this placeholder.
